name: build
on:
  push:
    branches:
      - 'md3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Rename dist
        run: mv dist Matecho

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Matecho
          path: Matecho/