name: build
on:
  push:
    branches:
      - "md3"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          lfs: true

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm type-check

      - name: Build
        run: pnpm build

      - name: Rename dist
        run: mkdir Matecho && mv dist Matecho/Matecho

      - name: Upload artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: Matecho-${{ github.sha }}
          path: Matecho
      - name: Update deployment
        run: "curl -s -m 5 -H 'X-Authorization: ${{ secrets.update_access_token }}' https://matecho-dev.zapic.moe/index.php/UpdateMatecho?artifact_id=${{ steps.artifact-upload.outputs.artifact-id }} || true"
